[package]
name = "desktop_lambdas"
version = "0.1.0"
authors = ["Ernesto Rodriguez <ernesto.rodriguez@quantifio.no>"]
edition = "2018"

[lib]
name = "desktop_lambdas"
path = "src/desktop_lambdas/lib.rs"

[dependencies]
regex = "1"